---
- name: Assert required variables
  assert:
    that:
      - github_repo | length > 0
      - github_asset_name | length > 0

- name: Resolve latest GitHub release url
  include_role:
    name: me.utils/github_release_resolver

- name: Download and Extract
  include_role:
    name: me.utils/download_file
  vars:
    download_dir: "{{tmp_dir}}"
    download_url: "{{github_download_url}}"
    filename: "{{github_asset_name}}"
