---
- name: Install terminator
  become: true
  apt:
    name:
      - terminator
    state: present

- name: Create ~/.config/terminator if not exists
  file:
    path: ~/.config/terminator
    state: directory
    mode: '0755'

- name: Copy ./files/terminator/config to ~/.config/terminator/config
  copy:
    src: ./files/terminator/config
    dest: ~/.config/terminator/config
    mode: '0644'
