---
- name: Install LazySql
  include_role:
    name: me.utils/install_github_binary
  vars:
    github_repo: "jorgerojas26/lazysql"
    github_asset_name: "lazysql_Linux_x86_64.tar.gz"
    binary_src_name: "lazysql"
    binary_dest_name: "lazysql"
    extract_archive: true
