---
- name: Test if devtoys is installed
  command: which devtoys
  register: test_devtoys
  changed_when: false
  failed_when: false

- name: Download devtoys_linux_x64.deb
  when: test_devtoys.rc != 0
  get_url:
    url: https://github.com/DevToys-app/DevToys/releases/download/v2.0.8.0/devtoys_linux_x64.deb
    dest: /tmp/devtoys_linux_x64.deb
    mode: '0644'

- name: Install google chrome
  when: test_devtoys.rc != 0
  become: true
  apt:
    deb: /tmp/devtoys_linux_x64.deb
    state: present

- name: Delete /tmp/devtoys_linux_x64.deb
  file:
    path: /tmp/devtoys_linux_x64.deb
    state: absent
