---
- name: Git global .gitignore
  community.general.git_config:
    name: core.excludesfile
    value: "{{ ansible_env.HOME }}/setup/.gitignore"
    scope: global

- name: Git text editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Git pull rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: Git configure email
  when: var_git_email is defined and var_git_email != ''
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ var_git_email }}"

- name: Git configure username
  when: var_git_username is defined and var_git_username != ''
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ var_git_username }}"

- name: Install lazygit
  # noqa no-changed-when
  command: /usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

- name: Test if git-lfs is installed
  command: which git-lfs
  register: test_git_lsf
  changed_when: false
  failed_when: false

- name: Install git-lfs repository
  become: true
  when: test_git_lsf.rc != 0
  # noqa no-changed-when
  shell: |
    set -o pipefail
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  args:
    executable: /bin/bash

- name: Install git-lfs
  become: true
  when: test_git_lsf.rc != 0
  apt:
    name:
      - git-lfs
    update_cache: true
    state: present

- name: Install git lfs
  # noqa no-changed-when
  command: git lfs install
