---
- name: Test if terraform is installed
  command: which terraform
  register: test_terraform
  changed_when: false
  failed_when: false

- name: Install the HashiCorp GPG key
  when: test_terraform.rc != 0
  # noqa no-changed-when
  shell: |
    set -o pipefail
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
  args:
    executable: /bin/bash

- name: Add the official HashiCorp repository to your system
  when: test_terraform.rc != 0
  # noqa no-changed-when
  shell: |
    set -o pipefail
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ansible_lsb.codename | lower}} main" \
    | sudo tee /etc/apt/sources.list.d/hashicorp.list
  args:
    executable: /bin/bash

- name: Install terraform
  become: true
  when: test_terraform.rc != 0
  apt:
    name:
      - terraform
    update_cache: true
    state: present
