---
- name: Download tree-sitter
  get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.23.1/tree-sitter-linux-x64.gz
    dest: /tmp/tree-sitter.gz
    mode: '0644'

- name: Gunzip tree-sitter
  command: gunzip -f /tmp/tree-sitter.gz

- name: Install tree-sitter binary
  become: true
  copy:
    src: /tmp/tree-sitter
    dest: /usr/local/bin/tree-sitter
    mode: '0755'
    remote_src: true
